version: '2'

services:

  plex:
    image: greensheep/plex-server-docker-rpi:latest
    container_name: plex
    ports:
      - 3400:32400
    volumes:
      - config-volume:/config
      - data-volume:/data
    depends_on:
      - mysql

volumes:
    config-volume:/home/pi/Documents/pi-server/Docker/Plex/config
    data-volume:/home/pi/Documents/pi-server/Docker/Plex/data
