# ownCloud with MariaDB/MySQL
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: <Choose your password>
# Database name: pick any name
# Database host: replace "localhost" with "mariadb-01"

version: '2'

services:

  owncloud:
    image: blepiolot/rpi-owncloud:latest
    container_name: owncloud-01
    ports:
      - 8080:80
      - 443:443
    volumes:
      - html-volume:/var/www/html
      - apache2-conf-volume:/etc/apache2
      - letsencrypt-conf-volume:/etc/letsencrypt
    depends_on:
      - mysql

  mysql:
    image: blepiolot/rpi-mariadb:latest
    container_name: mariadb-01
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
    html-volume:
    apache2-conf-volume:
    letsencrypt-conf-volume:
    db-volume:
